before:
  hooks:
  - go generate ./...
builds:
- main: ./cmd/indexer/.
  binary: indexer
  ldflags:
  - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  env:
  - CGO_ENABLED=0
checksum:
  name_template: "checksums.txt"
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
